
---

- hosts: all
  become: true
  pre_tasks:

  - name: dnf and epel installation
    package:
      name:
        - dnf
        - epel-release
      state: latest
    when: ansible_distribution == "CentOS"

  - name: dpkg in Ubuntu
    shell:
      cmd: "dpkg --configure -a"
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS)
    package:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
        upgrade: dist
        update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu_nagios
  become: true
  roles:
    - ubuntu_nagios

- hosts: centos_nagios
  become: true
  roles:
    - centos_nagios
